# config/application.yml
defaults: &defaults
  patterns:
    categories:
      - matching
  anakin:
    load_balancer:
      host: 127.0.0.1
      port: 8080

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  anakin:
    load_balancer:
      host: 66.175.218.188 
      port: 8080
