# config/application.yml
defaults: &defaults
  patterns:
    categories:
      - matching
    limit:
      5
  anakin:
    load_balancer:
      host: 127.0.0.1
      port: 8080
    scene_text_ocr:
      host: 127.0.0.1
      port: 8081
  threescale:
    provider_key: deb3a45bcb74842cd38878b346e5d066
  user:
   account_types:
     - system
     - threescale

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  anakin:
    load_balancer:
      host: 66.175.218.188 
      port: 8080
    scene_text_ocr:
      host: 127.0.0.1
      port: 8081
