---
development:
  cloud_name: dgnixurwb
  api_key: '355741997987113'
  api_secret: ykQhWk3WAVvEMOQU4plVcmXNm9s
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dgnixurwb
  api_key: '355741997987113'
  api_secret: ykQhWk3WAVvEMOQU4plVcmXNm9s
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dgnixurwb
  api_key: '355741997987113'
  api_secret: ykQhWk3WAVvEMOQU4plVcmXNm9s
  enhance_image_tag: true
  static_image_support: false
